export const timeData = {
  minutes: [{
    label: ':00',
    value: '00',
    format: 'm'
  }, {
    label: ':05',
    value: '05',
    format: 'm'
  }, {
    label: ':10',
    value: '10',
    format: 'm'
  }, {
    label: ':15',
    value: '15',
    format: 'm'
  }, {
    label: ':20',
    value: '20',
    format: 'm'
  }, {
    label: ':25',
    value: '25',
    format: 'm'
  }, {
    label: ':30',
    value: '30',
    format: 'm'
  }, {
    label: ':35',
    value: '35',
    format: 'm'
  }, {
    label: ':40',
    value: '40',
    format: 'm'
  }, {
    label: ':45',
    value: '45',
    format: 'm'
  }, {
    label: ':50',
    value: '50',
    format: 'm'
  }, {
    label: ':55',
    value: '55',
    format: 'm'
  }],
  hours: [{
    label: '00',
    value: '00',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '01',
    value: '01',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '02',
    value: '02',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '03',
    value: '03',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '04',
    value: '04',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '05',
    value: '05',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '06',
    value: '06',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '07',
    value: '07',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '08',
    value: '08',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '09',
    value: '09',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '10',
    value: '10',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '11',
    value: '11',
    type: '24',
    ap: 'a',
    format: 'h'
  }, {
    label: '12',
    value: '12',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '13',
    value: '13',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '14',
    value: '14',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '15',
    value: '15',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '16',
    value: '16',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '17',
    value: '17',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '18',
    value: '18',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '19',
    value: '19',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '20',
    value: '20',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '21',
    value: '21',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '22',
    value: '22',
    type: '24',
    ap: 'p',
    format: 'h'
  }, {
    label: '23',
    value: '23',
    type: '24',
    ap: 'p',
    format: 'h'
  }],
  hoursAM: [{
    label: 'Midnight',
    value: '00',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '01 AM',
    value: '01',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '02 AM',
    value: '02',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '03 AM',
    value: '03',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '04 AM',
    value: '04',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '05 AM',
    value: '05',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '06 AM',
    value: '06',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '07 AM',
    value: '07',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '08 AM',
    value: '08',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '09 AM',
    value: '09',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '10 AM',
    value: '10',
    type: '12',
    ap: 'a',
    format: 'h'
  }, {
    label: '11 AM',
    value: '11',
    type: '12',
    ap: 'a',
    format: 'h'
  }],
  hoursPM: [{
    label: 'Noon',
    value: '00',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '01 PM',
    value: '01',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '02 PM',
    value: '02',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '03 PM',
    value: '03',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '04 PM',
    value: '04',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '05 PM',
    value: '05',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '06 PM',
    value: '06',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '07 PM',
    value: '07',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '08 PM',
    value: '08',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '09 PM',
    value: '09',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '10 PM',
    value: '10',
    type: '12',
    ap: 'p',
    format: 'h'
  }, {
    label: '11 PM',
    value: '11',
    type: '12',
    ap: 'p',
    format: 'h'
  }]
}
