version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: Bootstraping packages
          command: npm run init

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      # run tests
      - run:
          name: Run tests
          command: npm test -- --maxWorkers=2 --ci --coverage --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit.xml"

      - store_test_results:
          name: Store test results
          path: reports

      - store_artifacts:
          name: Store coverage
          path: coverage

      # send coverage to CodeCov
      - run:
          name: Upload test coverage
          command: node ./node_modules/.bin/codecov

      # test code style
      - run:
          name: Run linter
          command: npm run lint

      # test local versions
      - run:
          name: Test local versions
          command: npm run compare-own-versions -- --all

      # test dependencies versions in README file
      - run:
          name: Test README dependencies
          command: npm run readme-dependencies -- --all

      # test dependencies versions in package.json
      - run:
          name: Test package dependencies
          command: npm run compare-dependencies -- --all

      # test missing or not used dependencies
      - run:
          name: Check missing dependencies
          command: npm run check-missing-dependencies -- --all
