export default {
  bar: 'local_bar',
  cafe: 'local_cafe',
  car_wash: 'local_car_wash',
  food: 'local_dining',
  restaurant: 'local_dining',
  drink: 'local_drink',
  gas_station: 'local_gas_station',
  hotel: 'local_hotel',
  hospital: 'local_hospital',
  store: 'local_grocery_store',
  activity: 'local_play',
  airport: 'local_airport',
  parking: 'local_parking',
  central_train_station: 'train',
  poi_train_station: 'train',
  transit_station: 'train',
  subway_station: 'train',
  train_station: 'train',
  light_rail_station: 'train',
  bus_station: 'directions_bus',
  taxi_stand: 'local_taxi',
  atm: 'local_atm',
  pharmacy: 'local_pharmacy',
  default: 'location_on'
}
